version: 2
jobs:
  build:
    working_directory: ~/base-java-project
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - restore_cache:
          key: base-java-project-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: base-java-project-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/base.jar